Character1: {wave:2} Hello! {/wave} What would you like to do?
[branch1] Option 1 [/branch1] [target:2]
[branch2] Option 2 [/branch2] [target:3]

Character1: You chose option 1. (end)

Character1: You chose option 2.
[branch1] wanna leave ? [/branch1] [target:5]
[branch2] wanna stay ? [/branch2] [target:6]

Character1:Verywell.
Character1: You chose to leave. (end)
Character1: You chose to stay. (end)
