name: Run Love2D Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Love2D
        run: |
          sudo apt-get update
          sudo apt-get install -y love

      - name: Run Love2D Tests
        run: love tests/
